name: Install
description: Install dev dependencies as of DEV_DEPENDENCIES_BEFORE and runtime dependencies at their latest version in range
runs:
  using: composite
  steps:
    - name: Install dev dependencies
      shell: bash
      run: |
        npm pkg delete dependencies
        npm install --ignore-scripts --before=$DEV_DEPENDENCIES_BEFORE
        git checkout package.json
    - name: Install latest runtime dependencies in range
      shell: bash
      run: |
        RUNTIME_DEPENDENCIES=$(node -p "Object.entries(require('./package.json').dependencies).map(([name, range]) => name + '@' + range).join(' ')")
        npm install --ignore-scripts --no-save $RUNTIME_DEPENDENCIES pem@$PEM_VERSION @types/node@$TYPES_NODE_VERSION
